version: '3.8'

services:
  # Development service with hot-reloading
  data-formulator-dev:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    ports:
      - "5000:5000"  # Backend port
      - "5173:5173"  # Frontend development port
    volumes:
      - ..:/app  # Mount source code for development
      - ./config:/app/config  # Mount config directory
      - node_modules:/app/node_modules  # Persist node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      # Uncomment and set your API keys as needed:
      # - OPENAI_API_KEY=your_key_here
      # - AZURE_API_KEY=your_key_here
      # - ANTHROPIC_API_KEY=your_key_here
    command: sh -c "yarn && yarn start"  # Start in development mode
    restart: unless-stopped

  # Production service
  data-formulator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: production
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
    environment:
      - PORT=5000
      - NODE_ENV=production
      # Uncomment and set your API keys as needed:
      # - OPENAI_API_KEY=your_key_here
      # - AZURE_API_KEY=your_key_here
      # - ANTHROPIC_API_KEY=your_key_here
    restart: unless-stopped

volumes:
  node_modules:  # Named volume for node_modules
